// DEVELOPER NOTE: Replace all property data below with actual property details.
// Update property address, price, descriptions, photos, agent info, etc.
// Photo URLs should be replaced with actual hosted images before launch.
const PROPERTIES = [
  {
    id: "prop-001",
    title: "Colorado Springs Family Home",
    address: "6390 Tranters Creek Way, Colorado Springs, Colorado 80925",
    lat: 39.7392,
    lng: -104.9903,
    status: "Active",
    price: 625000,
    sqft: 2850,
    bedrooms: 4,
    bathrooms: 3,
    lotSize: "0.25 acres",
    description: "Spacious two-story home featuring an open-concept layout, generous living spaces, and a large fenced backyard. The main level offers a bright kitchen with granite countertops, stainless steel appliances, abundant cabinetry, and a center island overlooking the dining area. Multiple living areas provide flexibility for entertaining, relaxing, or working from home. The private backyard includes ample outdoor space for recreation, gatherings, and play.",
    renovationDetails: "Features include granite countertops, stainless steel appliances, hardwood flooring in main living areas, and well-maintained interior finishes. Contact listing agent for a complete list of upgrades and improvements.",
    permitInfo: "Buyer to verify any permits, improvements, and property information with the appropriate local authorities.",
    hoaInfo: "Contact listing agent for HOA information, fees, covenants, and community details.",
    zoningInfo: "Buyer to verify zoning and permitted uses with El Paso County and local authorities.",
    photos: [
      "Prop-01/1.jpg",
      "Prop-01/2.jpg",
      "Prop-01/3.jpg",
      "Prop-01/4.jpg",
      "Prop-01/5.jpg",
      "Prop-01/6.jpg",
      "Prop-01/7.jpg",
      "Prop-01/8.jpg",
      "Prop-01/9.jpg",
      "Prop-01/10.jpg",
      "Prop-01/11.jpg",
      "Prop-01/12.jpg",
      "Prop-01/13.jpg",
      "Prop-01/14.jpg",
      "Prop-01/15.jpg",
      "Prop-01/16.jpg",
      "Prop-01/17.jpg",
      "Prop-01/18.jpg",
      "Prop-01/19.jpg",
      "Prop-01/20.jpg",
      "Prop-01/21.jpg",
      "Prop-01/22.jpg",
      "Prop-01/23.jpg",
      "Prop-01/24.jpg",
      "Prop-01/25.jpg",
      "Prop-01/26.jpg",
      "Prop-01/27.jpg",
      "Prop-01/28.jpg",
      "Prop-01/28b.jpg",
      "Prop-01/29.jpg",
      "Prop-01/30.jpg",
      "Prop-01/31.jpg",
      "Prop-01/32.jpg",
      "Prop-01/33.jpg",
      "Prop-01/34.jpg",
      "Prop-01/35.jpg",
      "Prop-01/36.jpg",
      "Prop-01/37.jpg",
      "Prop-01/38.jpg",
      "Prop-01/39.jpg",
      "Prop-01/40.jpg",
      "Prop-01/41.jpg",
      "Prop-01/42.jpg",
      "Prop-01/43.jpg",
      "Prop-01/44.jpg",
      "Prop-01/45.jpg",
      "Prop-01/46.jpg",
      "Prop-01/47.jpg",
      "Prop-01/48.jpg",
      "Prop-01/49.jpg",
      "Prop-01/50.jpg",
      "Prop-01/51.jpg",
      "Prop-01/52.jpg",
      "Prop-01/53.jpg",
      "Prop-01/54.jpg",
      "Prop-01/55.jpg",
      "Prop-01/56.jpg",
      "Prop-01/57.jpg",
      "Prop-01/58.jpg",
      "Prop-01/59.jpg",
      "Prop-01/60.jpg",
      "Prop-01/61.jpg",
      "Prop-01/62.jpg",
      "Prop-01/63.jpg",
      "Prop-01/64.jpg",
      "Prop-01/65.jpg",
      "Prop-01/66.jpg",
      "Prop-01/67.jpg",
      "Prop-01/68.jpg",
      "Prop-01/69.jpg",
      "Prop-01/70.jpg",
      "Prop-01/71.jpg",
      "Prop-01/72.jpg",
      "Prop-01/73.jpg",
      "Prop-01/74.jpg",
      "Prop-01/75.jpg",
      "Prop-01/76.jpg"
    ],
    listingAgent: "Brandy Renon",
    licensingDisclosure: "Independent Level Real Estate Broker - Individual Proprietor",
    fairHousing: "Equal Housing Opportunity."
  },
  {
    id: "prop-002",
    title: "Charming Highlands Bungalow",
    address: "5678 Aspen Lane, Boulder, CO 80302",
    lat: 40.0150,
    lng: -105.2705,
    status: "Pending",
    price: 489000,
    sqft: 1650,
    bedrooms: 3,
    bathrooms: 2,
    lotSize: "0.18 acres",
    description: "Charming bungalow nestled in a quiet neighborhood with easy access to hiking trails, local dining, and Boulder lifestyle amenities.",
    renovationDetails: "Fresh exterior paint, new roof (2022), updated electrical panel.",
    permitInfo: "Roof replacement and electrical update completed with permits. Contact agent for details.",
    hoaInfo: "No HOA.",
    zoningInfo: "Zoned R-2 Low-Density Residential.",
    photos: [
      "https://images.unsplash.com/photo-1449844908441-8829872d2607?w=800",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800",
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800"
    ],
    listingAgent: "Brandy Renon",
    licensingDisclosure: "Independent Level Real Estate Broker - Individual Proprietor",
    fairHousing: "Equal Housing Opportunity."
  },
  {
    id: "prop-003",
    title: "Spacious Suburban Family Home",
    address: "910 Ponderosa Drive, Colorado Springs, CO 80903",
    lat: 38.8339,
    lng: -104.8214,
    status: "Active",
    price: 545000,
    sqft: 3200,
    bedrooms: 5,
    bathrooms: 3.5,
    lotSize: "0.35 acres",
    description: "Spacious family home in a desirable Colorado Springs neighborhood with generous gathering spaces, mature landscaping, and a flexible floor plan.",
    renovationDetails: "Primary suite added in 2021 with spa-like bathroom. Open-concept main floor remodel.",
    permitInfo: "Addition built with full permits and inspections. Available upon request.",
    hoaInfo: "HOA fee: $85/month. Covers community pool, tennis courts, and park maintenance.",
    zoningInfo: "Zoned R-1 Single Family Residential.",
    photos: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800"
    ],
    listingAgent: "Brandy Renon",
    licensingDisclosure: "Independent Level Real Estate Broker - Individual Proprietor",
    fairHousing: "Equal Housing Opportunity."
  },
];

const AGENT_INFO = {
  name: "Brandy Renon",
  license: "II100070680",
  phone: "(719)291-8378",
  email: "propertiesinco@gmail.com",
};

window.PROPERTIES = PROPERTIES;
window.AGENT_INFO = AGENT_INFO;
